### ISSUE TITLE
React 18 support

### ISSUE THREAD

**Issue by jpveooys** [laleksiunas/inline-svg-unique-id#3]
Hi,

It would be good to add React 18 support and update the peer dependency range for `@inline-svg-unique-id/react`:

https://github.com/laleksiunas/inline-svg-unique-id/blob/dd6aa00f6673008ec5830f70bdebc341e142f83b/packages/react-inline-svg-unique-id/package.json#L32

Thanks

**Comment by laleksiunas** [comment]
Hi,
Thank you for raising this issue. I will look into it this week, as I aim to support React 18 as well.

**Comment by laleksiunas** [comment]
React 18 was added to the peer dependency range.
